import test from "node:test";
import assert from "node:assert/strict";
import { submitSoundingsTurnInCaller } from "../../apps/rpg-ui/src/runtime/soundingsTurnInCaller.ts";
import { createPlayerQuestAcceptanceCommand, executePlayerQuestAcceptanceCommand } from "../../packages/engines/game-engine/src/index.ts";
import { isTargetCampaignSnapshot } from "../../packages/engines/game-engine/src/campaign-rules.ts";
import { createOrdinarySoundingsCampaign, publishAndRestart, travelTo, withCampaignStorage, QUEST_ID, REQUEST_ID } from "../helpers/soundings-ordinary-campaign.mjs";

test("ordinary creator, four shifts, restart, return, submission, publication and later retry close Soundings exactly once", () => {
  withCampaignStorage(() => {
    let state = createOrdinarySoundingsCampaign({ returnToStarfall: false });
    const survey = structuredClone(state.snapshot.authorityLedger.ashenReefSurvey);
    assert.equal(survey.requests.length, 4);
    assert.equal(survey.occurrences.length, 4);
    assert.equal(survey.results.length, 4);
    assert.equal(survey.consequenceReceipts.length, 48);
    const tick = state.snapshot.clock.tick;
    const fareBaseline = structuredClone(state.snapshot.playerState.currency);
    state = travelTo(state, "settlement.starfall_port");
    assert.equal(state.snapshot.clock.tick, tick + 4);
    assert.deepEqual(state.snapshot.playerState.currency, fareBaseline);
    assert.equal(state.snapshot.playerState.location.settlementId, "settlement.starfall_port");
    const before = structuredClone(state.snapshot);
    const transition = submitSoundingsTurnInCaller(state.snapshot, state.control, REQUEST_ID, new Map());
    assert.equal(transition.outcome.kind, "accepted", transition.outcome.notice?.detail);
    assert.ok(transition.acceptedState);
    state = transition.acceptedState;
    assert.equal(isTargetCampaignSnapshot(state.snapshot), true);
    assert.equal(state.snapshot.playerState.currency.gold, before.playerState.currency.gold + 5);
    assert.equal(state.snapshot.playerState.currency.silver, before.playerState.currency.silver);
    assert.equal(state.snapshot.playerState.currency.copper, before.playerState.currency.copper);
    for (const key of ["standing", "reputation", "skills", "inventory", "geographicKnowledge", "discoveryChronicle"]) {
      assert.deepEqual(state.snapshot.playerState[key], before.playerState[key], key);
    }
    assert.deepEqual(state.snapshot.authorityLedger.ashenReefSurvey, survey);
    assert.equal(state.snapshot.sessionState.questJournal.find(row => row.id === QUEST_ID).category, "completed");
    assert.notEqual(state.snapshot.sessionState.trackedQuestId, QUEST_ID);
    assert.equal(state.snapshot.sessionState.operations.some(row => row.id === "operation.quest.ashen_reef_survey"), false);
    const ledger = structuredClone(state.snapshot.authorityLedger.soundingsTurnIn);
    assert.equal(ledger.requests.length, 1);
    assert.equal(ledger.occurrences.length, 1);
    assert.equal(ledger.results.length, 1);
    assert.equal(ledger.consequenceReceipts.filter(row => row.kind === "currency_credit").length, 1);
    const chronicleReceipt = ledger.consequenceReceipts.find(row => row.kind === "chronicle_projection");
    const chronicle = state.snapshot.sessionState.chronicle.find(row => row.id === chronicleReceipt.effect.projectionId);
    assert.ok(chronicle);
    assert.match(JSON.stringify(chronicle), /5 gold/);
    assert.match(JSON.stringify(chronicle), /Starfall/);
    state = publishAndRestart(state.snapshot, state.control);
    assert.deepEqual(state.snapshot.authorityLedger.soundingsTurnIn, ledger);
    assert.deepEqual(state.snapshot.authorityLedger.ashenReefSurvey, survey);
    const completed = structuredClone(state.snapshot);
    const duplicate = submitSoundingsTurnInCaller(state.snapshot, state.control, REQUEST_ID, new Map());
    assert.equal(duplicate.outcome.result.code, "duplicate");
    assert.equal(duplicate.acceptedState, null);
    assert.equal(duplicate.outcome.result.snapshot, state.snapshot);
    assert.deepEqual(state.snapshot, completed);
    const reaccept = executePlayerQuestAcceptanceCommand(state.snapshot, createPlayerQuestAcceptanceCommand(state.snapshot, QUEST_ID));
    assert.equal(reaccept.accepted, false);
    assert.equal(reaccept.snapshot, state.snapshot);
    state = travelTo(state, "location.ashen_reef");
    assert.ok(state.snapshot.clock.tick > completed.clock.tick, "continued play uses an accepted travel mutation");
    const latest = structuredClone(state.snapshot);
    const laterDuplicate = submitSoundingsTurnInCaller(state.snapshot, state.control, REQUEST_ID, new Map());
    assert.equal(laterDuplicate.outcome.result.code, "duplicate");
    assert.equal(laterDuplicate.acceptedState, null);
    assert.equal(laterDuplicate.outcome.result.snapshot, state.snapshot);
    assert.deepEqual(state.snapshot, latest);
    assert.deepEqual(state.snapshot.authorityLedger.soundingsTurnIn, ledger);
    assert.deepEqual(state.snapshot.authorityLedger.ashenReefSurvey, survey);
    assert.equal(state.snapshot.playerState.currency.gold, completed.playerState.currency.gold);
    state = publishAndRestart(state.snapshot, state.control);
    assert.deepEqual(state.snapshot.authorityLedger.soundingsTurnIn, ledger);
    assert.equal(state.snapshot.sessionState.questJournal.filter(row => row.id === QUEST_ID).length, 1);
  }, 5 * 1024 * 1024);
});
